const mongoose = require('mongoose');

// Time Slot Schema - for storing time and availability
const timeSlotSchema = new mongoose.Schema({
  time: String,       // E.g., "9:00 AM"
  available: Boolean  // True if the time slot is available, false otherwise
});


// Function to generate time slots for a day (9 AM to 8 PM)
const generateTimeSlots = () => {
  const timeSlots = [];
  const times = [
    '9:00 AM', '10:00 AM', '11:00 AM', '12:00 PM', '1:00 PM', '2:00 PM', '3:00 PM', '4:00 PM', '5:00 PM', '6:00 PM', '7:00 PM', '8:00 PM'
  ];

  // Create time slots with available: false by default
  times.forEach(time => {
    timeSlots.push({
      time,
      available: false
    });
  });

  return timeSlots;
};

// Delivery Slot Schema - for each day of the week
const deliverySlotSchema = new mongoose.Schema({
  day: { type: String, enum: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'], required: true },
  isOpen: { type: Boolean, required: false }, // True if the restaurant is open on that day
  timeSlots: { type: [timeSlotSchema], default: generateTimeSlots } // Time slots with default value generated by the function
});

module.exports = mongoose.model('DeliverySlot', deliverySlotSchema);
